import Link from 'next/link';

export const metadata = { title: 'About', description: 'About Bheem Sharma and CodeBheem — Laravel-focused product development and freelance support.' };

export default function AboutPage() {
  return <>
    <section className="page-hero"><div className="container"><div className="breadcrumb">Home / About</div><div className="eyebrow">About</div><h1 className="title">A practical developer for <span className="gradient-text">backend-heavy products.</span></h1><p className="lead">My strongest work sits where product requirements meet backend logic: Laravel applications, SaaS workflows, APIs, admin systems, integrations and production troubleshooting.</p></div></section>
    <section className="section-sm"><div className="container about-grid"><div className="profile-panel reveal"><div className="avatar">BS</div><h2 style={{margin:'0 0 8px'}}>Bheem Sharma</h2><p className="muted" style={{margin:0}}>Full-Stack Developer · Laravel focused</p><div className="mini-grid"><div className="mini-item"><strong>2+ years</strong><span>Professional experience</span></div><div className="mini-item"><strong>PHP / Laravel</strong><span>Primary stack</span></div><div className="mini-item"><strong>SaaS & APIs</strong><span>Core project exposure</span></div><div className="mini-item"><strong>Remote-ready</strong><span>Freelance / contract work</span></div></div></div>
      <div className="reveal"><div className="eyebrow">How I approach work</div><h2 className="title-sm">Solve the business problem without making the codebase harder to own.</h2><p className="lead">I prefer clear scope, small verifiable milestones and solutions that another developer can understand later. That matters especially in client projects where requirements move and existing code cannot simply be rewritten.</p><p className="lead">My experience includes SaaS products, financial workflows, learning systems, ERP-style internal tools, e-commerce modules, REST APIs, payment integrations and deployment troubleshooting.</p><div className="tags" style={{marginTop:22}}>{['Laravel','PHP','Filament','MySQL','JavaScript','REST APIs','Nginx','SaaS'].map(tag=><span className="tag" key={tag}>{tag}</span>)}</div></div>
    </div></section>
    <section className="section"><div className="container"><div className="eyebrow reveal">Good fit</div><h2 className="title-sm reveal">Best ways to work together</h2><div className="grid-3" style={{marginTop:28}}><div className="card reveal"><h3>Agency overflow</h3><p>Your team has more Laravel work than current capacity. I take a defined backend module, bug queue or feature scope.</p></div><div className="card reveal"><h3>Product backlog</h3><p>You already have an application and need someone to clear bugs, add features or improve admin workflows.</p></div><div className="card reveal"><h3>Focused build</h3><p>You have a clear SaaS/admin/API requirement and need a developer to turn it into a working Laravel implementation.</p></div></div></div></section>
    <section className="section-sm"><div className="container"><div className="cta-banner reveal"><div className="eyebrow">Prefer to test the fit first?</div><h2 className="title-sm">Start with one contained task.</h2><p className="lead">A small first task is often the fastest way to judge code quality, communication and reliability.</p><div style={{marginTop:22}}><Link className="btn btn-primary" href="/contact">Send a small task →</Link></div></div></div></section>
  </>;
}
